name: GCC (Linux)

on:
  push:
    branches: [ master, ammarfaizi2-dev ]
  pull_request:
    branches: [ master, ammarfaizi2-dev ]
    
jobs:
  main:
    name: GCC Build and Test
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt install -y git gcc g++ make cmake libcurl4-openssl-dev valgrind doxygen;

    - name: GCC version
      run: gcc --version && g++ --version;

    #
    #  Debug mode
    #
    - name: (GCC Debug Mode) Build
      run: make BAN_WARN=1 CC=gcc CXX=g++ -j$(nproc);
    - name: (GCC Debug Mode) Run Test
      run: make BAN_WARN=1 CC=gcc CXX=g++ test -j$(nproc);

    - name: Clean Build
      run: make clean;

    #
    #  Release mode
    #
    - name: (GCC Release Mode) Build
      run: make RELEASE_MODE=1 BAN_WARN=1 CC=gcc CXX=g++ -j$(nproc);
    - name: (GCC Release Mode) Run Test
      run: make RELEASE_MODE=1 BAN_WARN=1 CC=gcc CXX=g++ SANITIZE=1 test -j$(nproc);
    
    - name: Store artifact
      uses: actions/upload-artifact@v2
      with:
        name: gwbot_gcc
        path: gwbot
