name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name : install depend for testing
                          run : sudo apt install -y git gcc g++ make cmake libcurl4-openssl-dev valgrind doxygen;
                        - name : build
                          run : make -j$(nproc);
                        - name : test
                          run : make test;
                        - name : dummy
                          run : echo dummy;
